import type { Crop, SoilType } from "./crops";

/**
 * Fruit library. Kept separate so the catalogue can grow without touching
 * the cereal / vegetable lists.
 */

interface FruitSeed {
  id: string;
  name: string;
  emoji: string;
  gradient: string;
  season: string;
  daysToHarvest: string;
  yield: string;
  soils: SoilType[];
  t: [number, number];
  r: [number, number];
  reason: string;
  steps: string[];
  water: string;
  pests: string[];
  harvest: string;
}

const seeds: FruitSeed[] = [
  {
    id: "papaya", name: "Papaya", emoji: "🥭", gradient: "from-orange-200 to-amber-500",
    season: "Year-round (tropical)", daysToHarvest: "8–11 months", yield: "30–60 t/ha",
    soils: ["loam", "sandy", "silty"], t: [21, 34], r: [15, 200],
    reason: "Fast-fruiting tropical tree for warm, free-draining ground.",
    steps: ["Raise seedlings in bags for 6–8 weeks.", "Plant 2 m x 2.5 m apart in composted pits.", "Keep one female or hermaphrodite plant per station.", "Mulch heavily and avoid waterlogging."],
    water: "Regular but never soggy — 20–25 mm per week.",
    pests: ["Papaya ringspot virus", "Mealybug", "Fruit fly"],
    harvest: "Pick when a yellow streak appears on the skin.",
  },
  {
    id: "orange", name: "Orange", emoji: "🍊", gradient: "from-orange-300 to-amber-600",
    season: "Perennial", daysToHarvest: "2–3 years to first crop", yield: "15–30 t/ha",
    soils: ["loam", "sandy", "silty"], t: [15, 32], r: [10, 150],
    reason: "Citrus thrives in warm, frost-free areas with deep drained soil.",
    steps: ["Plant grafted seedlings in 60 cm pits.", "Space 5 m x 5 m.", "Ring-weed and mulch the basin.", "Prune water shoots and dead wood yearly."],
    water: "Deep watering every 7–10 days in dry spells.",
    pests: ["Citrus greening", "Leaf miner", "Scale insects"],
    harvest: "Cut fruit with a short stalk when fully coloured and sweet.",
  },
  {
    id: "lemon", name: "Lemon", emoji: "🍋", gradient: "from-yellow-200 to-lime-500",
    season: "Perennial", daysToHarvest: "2–3 years to first crop", yield: "10–25 t/ha",
    soils: ["loam", "sandy"], t: [14, 33], r: [10, 140],
    reason: "Hardy citrus that fruits repeatedly and sells all year.",
    steps: ["Plant grafted trees 4 m apart.", "Keep the graft union above soil level.", "Feed with compost twice a year.", "Prune to an open centre."],
    water: "Even moisture; avoid drought at flowering.",
    pests: ["Citrus canker", "Aphids", "Mealybug"],
    harvest: "Pick when skin is glossy and slightly soft.",
  },
  {
    id: "lime", name: "Lime", emoji: "🍈", gradient: "from-lime-200 to-green-600",
    season: "Perennial", daysToHarvest: "2–3 years to first crop", yield: "8–20 t/ha",
    soils: ["sandy", "loam"], t: [18, 35], r: [10, 160],
    reason: "Small citrus for hot lowlands, tolerant of light soils.",
    steps: ["Plant 4 m x 4 m in composted pits.", "Mulch the basin to hold moisture.", "Prune low branches for easy picking."],
    water: "Weekly in dry weather.",
    pests: ["Leaf miner", "Fruit fly"],
    harvest: "Pick green and firm for the best juice.",
  },
  {
    id: "guava", name: "Guava", emoji: "🍐", gradient: "from-green-200 to-emerald-500",
    season: "Perennial", daysToHarvest: "2–3 years to first crop", yield: "15–30 t/ha",
    soils: ["loam", "sandy", "clay"], t: [17, 35], r: [10, 200],
    reason: "Very tolerant tree that fruits on poor soils with little care.",
    steps: ["Plant 5 m apart in composted pits.", "Prune after each harvest to force new fruiting wood.", "Bag fruit to stop fruit fly."],
    water: "Drought hardy once established.",
    pests: ["Fruit fly", "Anthracnose"],
    harvest: "Pick when the skin turns light green-yellow and smells sweet.",
  },
  {
    id: "passionfruit", name: "Passion Fruit", emoji: "🟣", gradient: "from-purple-300 to-fuchsia-600",
    season: "Perennial vine", daysToHarvest: "8–12 months", yield: "10–20 t/ha",
    soils: ["loam", "sandy", "silty"], t: [18, 30], r: [20, 180],
    reason: "High-value vine for warm highlands with steady moisture.",
    steps: ["Build a strong trellis 2 m high.", "Plant grafted vines 3 m apart.", "Train two arms along the wire.", "Prune trailing shoots after harvest."],
    water: "Regular — the vine wilts fast in drought.",
    pests: ["Fusarium wilt", "Brown spot", "Aphids"],
    harvest: "Collect fruit once it drops or turns deep purple.",
  },
  {
    id: "pomegranate", name: "Pomegranate", emoji: "🍎", gradient: "from-rose-300 to-red-600",
    season: "Perennial", daysToHarvest: "2–3 years to first crop", yield: "10–20 t/ha",
    soils: ["loam", "sandy", "chalky"], t: [15, 38], r: [0, 90],
    reason: "Excellent for hot, dry regions and alkaline soils.",
    steps: ["Plant cuttings or seedlings 4 m apart.", "Train to 3–5 main stems.", "Remove suckers regularly."],
    water: "Low — too much water splits the fruit.",
    pests: ["Fruit borer", "Bacterial blight"],
    harvest: "Pick when fruit sounds metallic when tapped.",
  },
  {
    id: "fig", name: "Fig", emoji: "🫒", gradient: "from-purple-200 to-violet-600",
    season: "Perennial", daysToHarvest: "1–2 years to first crop", yield: "6–15 t/ha",
    soils: ["chalky", "loam", "sandy"], t: [12, 35], r: [0, 90],
    reason: "Mediterranean tree that loves dry heat and stony, limey ground.",
    steps: ["Plant hardwood cuttings in winter.", "Space 5 m apart.", "Prune in the dormant season."],
    water: "Low once established.",
    pests: ["Fig rust", "Birds"],
    harvest: "Pick when the fruit droops and softens.",
  },
  {
    id: "grape", name: "Grape", emoji: "🍇", gradient: "from-violet-300 to-purple-700",
    season: "Warm dry season", daysToHarvest: "2–3 years to first crop", yield: "10–25 t/ha",
    soils: ["loam", "chalky", "sandy"], t: [12, 32], r: [0, 80],
    reason: "Vine that needs dry ripening weather and well-drained soil.",
    steps: ["Set posts and wires before planting.", "Plant rooted cuttings 2 m apart.", "Prune hard each dormant season.", "Thin bunches for bigger berries."],
    water: "Low at ripening to concentrate sugar.",
    pests: ["Downy mildew", "Powdery mildew", "Birds"],
    harvest: "Taste-test — pick when berries are sweet and seeds brown.",
  },
  {
    id: "apple", name: "Apple", emoji: "🍎", gradient: "from-red-200 to-rose-600",
    season: "Cool temperate", daysToHarvest: "3–4 years to first crop", yield: "15–40 t/ha",
    soils: ["loam", "silty", "clay"], t: [5, 24], r: [20, 140],
    reason: "Needs cold winters and cool summers; best on deep loam.",
    steps: ["Plant grafted trees in winter, 4 m apart.", "Stake young trees.", "Thin fruitlets to one per cluster.", "Prune annually for light."],
    water: "Deep watering during fruit swell.",
    pests: ["Codling moth", "Apple scab", "Aphids"],
    harvest: "Lift and twist — a ripe apple releases easily.",
  },
  {
    id: "pear", name: "Pear", emoji: "🍐", gradient: "from-lime-200 to-yellow-600",
    season: "Cool temperate", daysToHarvest: "3–5 years to first crop", yield: "15–35 t/ha",
    soils: ["loam", "clay", "silty"], t: [5, 24], r: [20, 140],
    reason: "Cool-climate tree that tolerates heavier soils than apple.",
    steps: ["Plant two varieties for pollination.", "Space 4–5 m apart.", "Prune lightly to keep fruiting spurs."],
    water: "Regular through fruit development.",
    pests: ["Pear psylla", "Fire blight"],
    harvest: "Pick firm and ripen off the tree.",
  },
  {
    id: "peach", name: "Peach", emoji: "🍑", gradient: "from-orange-200 to-rose-500",
    season: "Cool to warm temperate", daysToHarvest: "2–4 years to first crop", yield: "10–25 t/ha",
    soils: ["sandy", "loam"], t: [7, 30], r: [10, 110],
    reason: "Stone fruit for sunny sites with sharp drainage.",
    steps: ["Plant on a raised mound to avoid wet feet.", "Space 4 m apart.", "Prune to an open vase each winter.", "Thin fruit to 15 cm apart."],
    water: "Steady during stone hardening and swell.",
    pests: ["Peach leaf curl", "Fruit fly", "Brown rot"],
    harvest: "Pick when the ground colour turns from green to cream.",
  },
  {
    id: "plum", name: "Plum", emoji: "🫐", gradient: "from-indigo-300 to-purple-700",
    season: "Cool temperate", daysToHarvest: "3–4 years to first crop", yield: "10–20 t/ha",
    soils: ["loam", "clay", "silty"], t: [6, 28], r: [15, 130],
    reason: "Reliable stone fruit that handles heavier ground.",
    steps: ["Plant bare-root trees in winter.", "Space 4 m apart.", "Prune in summer to avoid silver leaf."],
    water: "Moderate; mulch to keep roots cool.",
    pests: ["Plum curculio", "Brown rot"],
    harvest: "Pick when fruit softens slightly at the stalk.",
  },
  {
    id: "cherry", name: "Cherry", emoji: "🍒", gradient: "from-rose-300 to-red-700",
    season: "Cool temperate", daysToHarvest: "3–5 years to first crop", yield: "5–15 t/ha",
    soils: ["loam", "silty", "chalky"], t: [4, 26], r: [15, 120],
    reason: "Cold-loving tree needing free drainage and a dry harvest window.",
    steps: ["Plant two compatible varieties.", "Space 5 m apart.", "Net against birds before ripening."],
    water: "Avoid heavy watering near harvest — fruit splits.",
    pests: ["Cherry fruit fly", "Birds", "Bacterial canker"],
    harvest: "Pick with stalks attached when fully coloured.",
  },
  {
    id: "apricot", name: "Apricot", emoji: "🍑", gradient: "from-amber-200 to-orange-600",
    season: "Cool dry temperate", daysToHarvest: "3–4 years to first crop", yield: "8–18 t/ha",
    soils: ["sandy", "loam", "chalky"], t: [5, 30], r: [0, 90],
    reason: "Early-flowering stone fruit for dry, sunny, frost-free springs.",
    steps: ["Plant on a sheltered slope.", "Space 5 m apart.", "Prune after harvest, not in winter."],
    water: "Low to moderate.",
    pests: ["Brown rot", "Aphids"],
    harvest: "Pick when fruit is fragrant and gives to gentle pressure.",
  },
  {
    id: "coconut", name: "Coconut", emoji: "🥥", gradient: "from-emerald-200 to-teal-700",
    season: "Perennial (tropical)", daysToHarvest: "4–6 years to first crop", yield: "60–100 nuts/palm/yr",
    soils: ["sandy", "loam"], t: [22, 35], r: [30, 300],
    reason: "Coastal palm that tolerates salt, sand and heavy rain.",
    steps: ["Plant sprouted nuts in 1 m pits.", "Space 8 m x 8 m triangular.", "Ring-weed and add compost yearly."],
    water: "High rainfall or irrigation in dry months.",
    pests: ["Rhinoceros beetle", "Lethal yellowing"],
    harvest: "Cut mature nuts every 45–60 days.",
  },
  {
    id: "jackfruit", name: "Jackfruit", emoji: "🍈", gradient: "from-lime-300 to-amber-600",
    season: "Perennial (tropical)", daysToHarvest: "3–4 years to first crop", yield: "20–40 t/ha",
    soils: ["loam", "sandy", "silty"], t: [20, 36], r: [20, 250],
    reason: "Huge-yielding tropical tree that is very drought tolerant once grown.",
    steps: ["Plant grafted seedlings 8 m apart.", "Stake and shade young trees.", "Prop heavy fruit branches."],
    water: "Weekly for the first two years.",
    pests: ["Fruit borer", "Rhizopus rot"],
    harvest: "Fruit gives a hollow sound and strong aroma when ripe.",
  },
  {
    id: "lychee", name: "Lychee", emoji: "🔴", gradient: "from-rose-300 to-pink-600",
    season: "Subtropical", daysToHarvest: "4–6 years to first crop", yield: "8–15 t/ha",
    soils: ["loam", "clay", "silty"], t: [15, 33], r: [20, 200],
    reason: "Needs a cool dry spell to flower then warm wet weather to fruit.",
    steps: ["Plant air-layered trees 8 m apart.", "Mulch heavily — roots are shallow.", "Prune right after harvest."],
    water: "High during fruit swell, dry before flowering.",
    pests: ["Erinose mite", "Fruit borer", "Bats"],
    harvest: "Pick whole panicles when skin turns bright red.",
  },
  {
    id: "soursop", name: "Soursop", emoji: "🥝", gradient: "from-green-300 to-emerald-700",
    season: "Perennial (tropical)", daysToHarvest: "3–4 years to first crop", yield: "8–15 t/ha",
    soils: ["sandy", "loam"], t: [20, 34], r: [15, 220],
    reason: "Tropical tree for light soils; strong local and juice demand.",
    steps: ["Plant seedlings 5 m apart.", "Hand-pollinate flowers for better set.", "Mulch and shelter from wind."],
    water: "Regular; dislikes waterlogging.",
    pests: ["Mealybug", "Anthracnose"],
    harvest: "Pick when spines soften and fruit lightens in colour.",
  },
  {
    id: "custardapple", name: "Custard Apple", emoji: "🍏", gradient: "from-emerald-200 to-lime-600",
    season: "Warm dry season", daysToHarvest: "2–4 years to first crop", yield: "6–12 t/ha",
    soils: ["sandy", "loam", "chalky"], t: [18, 36], r: [0, 120],
    reason: "Hardy semi-dry tree that fruits with little irrigation.",
    steps: ["Plant seedlings 5 m apart at the start of rains.", "Prune to keep trees low.", "Hand-pollinate for full fruit."],
    water: "Low — drought tolerant.",
    pests: ["Mealybug", "Fruit borer"],
    harvest: "Pick when segments start to separate.",
  },
  {
    id: "tamarind", name: "Tamarind", emoji: "🟤", gradient: "from-amber-300 to-orange-800",
    season: "Perennial (semi-arid)", daysToHarvest: "5–7 years to first crop", yield: "10–20 t/ha",
    soils: ["sandy", "loam", "clay"], t: [20, 40], r: [0, 120],
    reason: "Very drought hardy tree for hot dry lands.",
    steps: ["Plant grafted seedlings 10 m apart.", "Protect from grazing for 3 years.", "Little pruning needed."],
    water: "Rainfall alone once established.",
    pests: ["Fruit borer", "Scale"],
    harvest: "Collect pods when shells are brittle.",
  },
  {
    id: "mulberry", name: "Mulberry", emoji: "🫐", gradient: "from-fuchsia-300 to-purple-800",
    season: "Warm season", daysToHarvest: "1–2 years to first crop", yield: "5–12 t/ha",
    soils: ["loam", "sandy", "silty"], t: [10, 34], r: [10, 160],
    reason: "Fast, easy tree that fruits within a year of planting.",
    steps: ["Plant hardwood cuttings in the rains.", "Space 3 m apart.", "Cut back hard each year for new fruiting wood."],
    water: "Moderate.",
    pests: ["Birds", "Leaf spot"],
    harvest: "Pick daily as berries darken.",
  },
  {
    id: "dragonfruit", name: "Dragon Fruit", emoji: "🐉", gradient: "from-pink-300 to-rose-700",
    season: "Warm season", daysToHarvest: "12–18 months", yield: "15–30 t/ha",
    soils: ["sandy", "loam", "chalky"], t: [18, 38], r: [0, 120],
    reason: "Cactus vine for hot dry areas with very free-draining soil.",
    steps: ["Set concrete posts with a top frame.", "Plant 3–4 cuttings per post.", "Train one main stem to the top.", "Night-pollinate by hand if fruit set is poor."],
    water: "Little — rot follows overwatering.",
    pests: ["Stem canker", "Ants", "Birds"],
    harvest: "Pick 30–35 days after flowering when skin is fully coloured.",
  },
  {
    id: "starfruit", name: "Star Fruit", emoji: "⭐", gradient: "from-yellow-200 to-amber-600",
    season: "Perennial (tropical)", daysToHarvest: "2–3 years to first crop", yield: "10–25 t/ha",
    soils: ["loam", "sandy", "silty"], t: [20, 35], r: [20, 220],
    reason: "Continuous-cropping tropical tree that likes humid warmth.",
    steps: ["Plant grafted trees 6 m apart.", "Mulch and shelter from wind.", "Bag fruit against fruit fly."],
    water: "Regular; fruit drops in drought.",
    pests: ["Fruit fly", "Anthracnose"],
    harvest: "Pick when ribs turn yellow with brown edges.",
  },
  {
    id: "breadfruit", name: "Breadfruit", emoji: "🥥", gradient: "from-green-300 to-emerald-800",
    season: "Perennial (tropical)", daysToHarvest: "3–5 years to first crop", yield: "15–30 t/ha",
    soils: ["loam", "sandy", "silty"], t: [21, 36], r: [30, 300],
    reason: "Staple tropical tree crop needing warmth and steady rain.",
    steps: ["Plant root suckers 10 m apart.", "Shade young plants for the first year.", "Mulch thickly."],
    water: "High rainfall preferred.",
    pests: ["Mealybug", "Fruit rot"],
    harvest: "Cut when latex drops appear on the skin.",
  },
  {
    id: "date", name: "Date Palm", emoji: "🌴", gradient: "from-amber-200 to-yellow-800",
    season: "Hot arid", daysToHarvest: "4–7 years to first crop", yield: "8–15 t/ha",
    soils: ["sandy", "chalky", "loam"], t: [20, 45], r: [0, 40],
    reason: "The classic desert fruit — hot, dry and salty soils are fine.",
    steps: ["Plant offshoots 8 m apart.", "Hand-pollinate female palms.", "Thin bunches and bag against birds."],
    water: "Irrigate at the base; needs dry air.",
    pests: ["Red palm weevil", "Birds"],
    harvest: "Harvest bunches as fruit turns amber and soft.",
  },
  {
    id: "olive", name: "Olive", emoji: "🫒", gradient: "from-lime-300 to-emerald-800",
    season: "Mediterranean", daysToHarvest: "3–5 years to first crop", yield: "3–10 t/ha",
    soils: ["chalky", "sandy", "loam"], t: [8, 35], r: [0, 80],
    reason: "Long-lived tree for dry summers and poor stony soils.",
    steps: ["Plant rooted cuttings 6 m apart.", "Prune to an open vase.", "Keep the ground weed-free."],
    water: "Very low once established.",
    pests: ["Olive fruit fly", "Peacock spot"],
    harvest: "Pick green for oil, black for table olives.",
  },
  {
    id: "blueberry", name: "Blueberry", emoji: "🫐", gradient: "from-sky-300 to-indigo-700",
    season: "Cool temperate", daysToHarvest: "2–3 years to first crop", yield: "5–12 t/ha",
    soils: ["peaty", "sandy"], t: [4, 26], r: [20, 150],
    reason: "Needs acidic, peaty, well-drained ground and cool summers.",
    steps: ["Raise beds with pine bark or peat.", "Plant 1 m apart.", "Mulch with sawdust and never lime the soil.", "Net against birds."],
    water: "Constant moisture; shallow roots dry fast.",
    pests: ["Birds", "Mummy berry"],
    harvest: "Pick berries 3–5 days after they turn fully blue.",
  },
  {
    id: "raspberry", name: "Raspberry", emoji: "🍇", gradient: "from-rose-300 to-pink-700",
    season: "Cool temperate", daysToHarvest: "1–2 years to first crop", yield: "5–12 t/ha",
    soils: ["loam", "peaty", "silty"], t: [4, 25], r: [20, 150],
    reason: "Cane fruit for cool, moist climates and rich soil.",
    steps: ["Set posts and two wires.", "Plant canes 50 cm apart.", "Cut fruited canes to the ground after harvest."],
    water: "Even moisture through fruiting.",
    pests: ["Raspberry beetle", "Cane blight"],
    harvest: "Pick daily — berries pull free of the core when ripe.",
  },
  {
    id: "blackberry", name: "Blackberry", emoji: "🫐", gradient: "from-slate-400 to-purple-900",
    season: "Cool to warm temperate", daysToHarvest: "1–2 years to first crop", yield: "8–15 t/ha",
    soils: ["loam", "clay", "silty"], t: [5, 30], r: [20, 160],
    reason: "Vigorous cane fruit that copes with less perfect soils.",
    steps: ["Trellis canes along wires.", "Plant 1.5 m apart.", "Remove old canes yearly."],
    water: "Moderate; mulch well.",
    pests: ["Birds", "Botrytis"],
    harvest: "Pick when berries are dull black and detach easily.",
  },
  {
    id: "kiwi", name: "Kiwifruit", emoji: "🥝", gradient: "from-lime-300 to-green-800",
    season: "Cool temperate", daysToHarvest: "3–4 years to first crop", yield: "15–30 t/ha",
    soils: ["loam", "silty", "peaty"], t: [4, 28], r: [20, 180],
    reason: "Vigorous vine needing shelter, deep soil and winter chill.",
    steps: ["Build a strong pergola or T-bar.", "Plant one male per six females.", "Prune in winter and summer."],
    water: "High in summer — leaves scorch in drought.",
    pests: ["Bacterial canker", "Scale"],
    harvest: "Pick firm in autumn and ripen off the vine.",
  },
  {
    id: "cantaloupe", name: "Melon (Cantaloupe)", emoji: "🍈", gradient: "from-orange-200 to-lime-500",
    season: "Warm season", daysToHarvest: "75–100 days", yield: "15–30 t/ha",
    soils: ["sandy", "loam", "silty"], t: [18, 35], r: [0, 70],
    reason: "Quick warm-season vine that needs dry ripening weather.",
    steps: ["Sow on low mounds 1 m apart.", "Mulch to keep fruit clean.", "Stop watering as fruit nets and ripens."],
    water: "Steady early, dry at ripening.",
    pests: ["Aphids", "Powdery mildew", "Fruit fly"],
    harvest: "Fruit slips from the vine and smells sweet.",
  },
  {
    id: "persimmon", name: "Persimmon", emoji: "🟠", gradient: "from-orange-300 to-red-700",
    season: "Warm temperate", daysToHarvest: "3–5 years to first crop", yield: "10–25 t/ha",
    soils: ["loam", "clay", "silty"], t: [8, 32], r: [15, 150],
    reason: "Tough tree with few pests, good for a range of soils.",
    steps: ["Plant grafted trees 5 m apart.", "Prune lightly in winter.", "Thin fruit to avoid branch break."],
    water: "Moderate.",
    pests: ["Mealybug", "Birds"],
    harvest: "Pick with the calyx attached when fully coloured.",
  },
  {
    id: "cashew", name: "Cashew", emoji: "🌰", gradient: "from-yellow-200 to-orange-700",
    season: "Perennial (semi-arid tropics)", daysToHarvest: "3–5 years to first crop", yield: "0.8–2 t/ha nuts",
    soils: ["sandy", "loam"], t: [20, 38], r: [0, 150],
    reason: "Drought-hardy tree giving both a nut and a juicy apple.",
    steps: ["Plant grafted seedlings 8 m apart.", "Weed a 1 m ring for 3 years.", "Prune low branches and dead wood."],
    water: "Rainfall is normally enough.",
    pests: ["Tea mosquito bug", "Anthracnose"],
    harvest: "Collect fallen nuts daily and dry in the sun.",
  },
];

export const FRUIT_CROPS: Crop[] = seeds.map((s) => ({
  id: s.id,
  name: s.name,
  emoji: s.emoji,
  gradient: s.gradient,
  season: s.season,
  daysToHarvest: s.daysToHarvest,
  yield: s.yield,
  soils: s.soils,
  tempMin: s.t[0],
  tempMax: s.t[1],
  rainMin: s.r[0],
  rainMax: s.r[1],
  reason: s.reason,
  steps: s.steps,
  water: s.water,
  pests: s.pests,
  harvest: s.harvest,
}));
