import type { Crop } from "./crops";

/**
 * Extended crop library. Combined with the base list in crops.ts so the
 * recommender can rank the full catalogue (no artificial cap).
 */
export const EXTRA_CROPS: Crop[] = [
  {
    id: "wheat",
    name: "Wheat",
    emoji: "🌾",
    gradient: "from-amber-200 to-yellow-600",
    season: "Cool season",
    daysToHarvest: "110–150 days",
    yield: "2–5 t/ha",
    soils: ["loam", "clay", "silty"],
    tempMin: 8, tempMax: 24, rainMin: 10, rainMax: 120,
    reason: "Cool-season cereal for heavier, moisture-holding soils.",
    steps: [
      "Prepare a firm, fine seedbed free of weeds.",
      "Drill seed 3–4 cm deep in rows 20 cm apart.",
      "Top-dress nitrogen at tillering.",
      "Control weeds early, before stem elongation.",
    ],
    water: "About 450–650 mm across the season; critical at flowering.",
    pests: ["Rust", "Aphids", "Armyworm"],
    harvest: "Cut when grain is hard and straw is golden.",
  },
  {
    id: "barley",
    name: "Barley",
    emoji: "🌾",
    gradient: "from-yellow-200 to-amber-500",
    season: "Cool season",
    daysToHarvest: "90–120 days",
    yield: "2–4 t/ha",
    soils: ["loam", "chalky", "sandy"],
    tempMin: 6, tempMax: 22, rainMin: 5, rainMax: 90,
    reason: "Hardy cereal that tolerates poorer, alkaline and dry soils.",
    steps: [
      "Sow into a firm seedbed 3 cm deep.",
      "Keep the crop weed-free for the first 6 weeks.",
      "Apply light nitrogen — too much causes lodging.",
    ],
    water: "Fairly drought-tolerant; needs moisture at grain fill.",
    pests: ["Powdery mildew", "Aphids"],
    harvest: "Heads nod and grain is hard to the fingernail.",
  },
  {
    id: "oats",
    name: "Oats",
    emoji: "🥣",
    gradient: "from-stone-200 to-amber-400",
    season: "Cool season",
    daysToHarvest: "90–120 days",
    yield: "2–4 t/ha",
    soils: ["loam", "peaty", "silty"],
    tempMin: 5, tempMax: 20, rainMin: 20, rainMax: 150,
    reason: "Handles cool, wet, acidic ground better than most cereals.",
    steps: [
      "Sow early in spring 2–4 cm deep.",
      "Roll after sowing to conserve moisture.",
      "Harvest promptly — oats shed grain when overripe.",
    ],
    water: "Likes steady moisture; poor drought tolerance.",
    pests: ["Frit fly", "Crown rust"],
    harvest: "Grain is firm and straw is pale yellow.",
  },
  {
    id: "millet",
    name: "Pearl Millet",
    emoji: "🌾",
    gradient: "from-lime-200 to-yellow-600",
    season: "Hot, dry season",
    daysToHarvest: "70–100 days",
    yield: "1–3 t/ha",
    soils: ["sandy", "loam", "chalky"],
    tempMin: 22, tempMax: 38, rainMin: 0, rainMax: 70,
    reason: "Extremely drought-hardy grain for hot, sandy land.",
    steps: [
      "Sow shallow (2 cm) at the first reliable rains.",
      "Thin to 15 cm between plants.",
      "Weed once at 3 weeks — millet competes poorly early.",
    ],
    water: "Survives on very little; avoid waterlogging.",
    pests: ["Downy mildew", "Birds"],
    harvest: "Cut heads when grain hardens and dries.",
  },
  {
    id: "cassava",
    name: "Cassava",
    emoji: "🍠",
    gradient: "from-amber-200 to-orange-500",
    season: "Warm, long season",
    daysToHarvest: "8–14 months",
    yield: "10–25 t/ha",
    soils: ["sandy", "loam"],
    tempMin: 20, tempMax: 35, rainMin: 10, rainMax: 200,
    reason: "Tolerates poor soils and dry spells; a reliable food security crop.",
    steps: [
      "Plant 25 cm healthy stem cuttings at an angle on ridges.",
      "Space 1 m x 1 m.",
      "Weed for the first 3 months until the canopy closes.",
    ],
    water: "Rain-fed; very drought tolerant once established.",
    pests: ["Cassava mosaic virus", "Mealybug"],
    harvest: "Lift roots when leaves yellow and drop.",
  },
  {
    id: "sweetpotato",
    name: "Sweet Potato",
    emoji: "🍠",
    gradient: "from-orange-200 to-rose-500",
    season: "Warm season",
    daysToHarvest: "90–150 days",
    yield: "10–25 t/ha",
    soils: ["sandy", "loam", "silty"],
    tempMin: 18, tempMax: 33, rainMin: 10, rainMax: 150,
    reason: "Fast, nutritious root crop for warm, well-drained soils.",
    steps: [
      "Plant 30 cm vine cuttings on ridges or mounds.",
      "Space 30 cm apart in rows 1 m apart.",
      "Lift vines occasionally to stop rooting at nodes.",
    ],
    water: "Moderate; reduce water near harvest.",
    pests: ["Sweet potato weevil", "Aphids"],
    harvest: "Dig when roots reach size, before heavy rain.",
  },
  {
    id: "yam",
    name: "Yam",
    emoji: "🥔",
    gradient: "from-stone-300 to-amber-600",
    season: "Warm, long season",
    daysToHarvest: "7–11 months",
    yield: "8–20 t/ha",
    soils: ["loam", "sandy", "silty"],
    tempMin: 22, tempMax: 34, rainMin: 30, rainMax: 250,
    reason: "High-value tuber for deep, fertile, well-drained soil.",
    steps: [
      "Make large mounds 1 m apart.",
      "Plant seed yam pieces 10 cm deep.",
      "Stake vines early for best yields.",
    ],
    water: "Needs good rainfall for the first 5 months.",
    pests: ["Yam beetle", "Nematodes", "Anthracnose"],
    harvest: "Vines yellow and die back; lift carefully.",
  },
  {
    id: "groundnut",
    name: "Groundnut (Peanut)",
    emoji: "🥜",
    gradient: "from-amber-200 to-orange-400",
    season: "Warm season",
    daysToHarvest: "90–130 days",
    yield: "1–3 t/ha",
    soils: ["sandy", "loam"],
    tempMin: 20, tempMax: 34, rainMin: 10, rainMax: 120,
    reason: "Nitrogen-fixing legume that loves light, free-draining soil.",
    steps: [
      "Sow shelled seed 5 cm deep, 15 cm apart.",
      "Keep soil loose so pegs can enter the ground.",
      "Apply gypsum at flowering for better pod fill.",
    ],
    water: "Even moisture at pegging and pod fill; dry at harvest.",
    pests: ["Leaf spot", "Aphids", "Rosette virus"],
    harvest: "Lift when inner shells show dark veining.",
  },
  {
    id: "soybean",
    name: "Soybean",
    emoji: "🫛",
    gradient: "from-lime-200 to-green-500",
    season: "Warm season",
    daysToHarvest: "90–130 days",
    yield: "1.5–3 t/ha",
    soils: ["loam", "silty", "clay"],
    tempMin: 18, tempMax: 32, rainMin: 20, rainMax: 150,
    reason: "Protein-rich legume that improves soil nitrogen.",
    steps: [
      "Inoculate seed with rhizobium before sowing.",
      "Sow 3–4 cm deep in rows 45 cm apart.",
      "Keep weed-free for the first 5 weeks.",
    ],
    water: "Critical at pod fill; avoid waterlogging.",
    pests: ["Rust", "Pod borer", "Whitefly"],
    harvest: "Pods rattle and leaves have dropped.",
  },
  {
    id: "cowpea",
    name: "Cowpea",
    emoji: "🫘",
    gradient: "from-emerald-200 to-teal-500",
    season: "Hot season",
    daysToHarvest: "60–90 days",
    yield: "0.8–2 t/ha",
    soils: ["sandy", "loam", "chalky"],
    tempMin: 20, tempMax: 36, rainMin: 0, rainMax: 90,
    reason: "Drought-tolerant legume that fixes nitrogen in poor soils.",
    steps: [
      "Sow 3 cm deep, 20 cm apart.",
      "Weed at 2 and 5 weeks.",
      "Spray or scout for flower thrips at budding.",
    ],
    water: "Low; excess rain reduces pod set.",
    pests: ["Thrips", "Pod borer", "Aphids"],
    harvest: "Pick pods as they dry, before they shatter.",
  },
  {
    id: "chickpea",
    name: "Chickpea",
    emoji: "🫛",
    gradient: "from-amber-100 to-lime-500",
    season: "Cool, dry season",
    daysToHarvest: "90–130 days",
    yield: "1–2.5 t/ha",
    soils: ["loam", "clay", "chalky"],
    tempMin: 10, tempMax: 28, rainMin: 0, rainMax: 70,
    reason: "Cool-season pulse for residual soil moisture and dry finishes.",
    steps: [
      "Sow 5 cm deep into moist soil.",
      "Avoid heavy nitrogen — it fixes its own.",
      "Keep foliage dry to limit blight.",
    ],
    water: "Low; sensitive to waterlogging.",
    pests: ["Ascochyta blight", "Pod borer"],
    harvest: "Plants yellow and pods are dry and rattling.",
  },
  {
    id: "lentil",
    name: "Lentil",
    emoji: "🫘",
    gradient: "from-orange-200 to-amber-500",
    season: "Cool season",
    daysToHarvest: "90–120 days",
    yield: "0.8–2 t/ha",
    soils: ["loam", "silty", "chalky"],
    tempMin: 8, tempMax: 26, rainMin: 0, rainMax: 80,
    reason: "Hardy cool-season pulse for light, well-drained ground.",
    steps: [
      "Sow shallow (3 cm) in a firm seedbed.",
      "Keep weeds down — lentils are poor competitors.",
      "Harvest promptly to avoid shattering.",
    ],
    water: "Low; dislikes wet feet.",
    pests: ["Aphids", "Rust"],
    harvest: "Lower pods turn brown and rattle.",
  },
  {
    id: "tomato",
    name: "Tomato",
    emoji: "🍅",
    gradient: "from-red-300 to-rose-600",
    season: "Warm season",
    daysToHarvest: "70–100 days",
    yield: "20–60 t/ha",
    soils: ["loam", "silty", "sandy"],
    tempMin: 16, tempMax: 30, rainMin: 5, rainMax: 90,
    reason: "High-value vegetable for warm days and well-drained fertile soil.",
    steps: [
      "Raise seedlings in a nursery for 4 weeks.",
      "Transplant 45 cm apart in rows 75 cm apart.",
      "Stake and prune side shoots on tall varieties.",
      "Mulch to keep fruit clean and soil moist.",
    ],
    water: "Regular, even watering prevents blossom end rot.",
    pests: ["Late blight", "Tuta absoluta", "Whitefly"],
    harvest: "Pick when fruit colours evenly and yields to light pressure.",
  },
  {
    id: "onion",
    name: "Onion",
    emoji: "🧅",
    gradient: "from-fuchsia-200 to-amber-500",
    season: "Cool to warm",
    daysToHarvest: "100–150 days",
    yield: "20–40 t/ha",
    soils: ["loam", "sandy", "silty"],
    tempMin: 12, tempMax: 28, rainMin: 0, rainMax: 70,
    reason: "Stores well and thrives in loose, free-draining soil.",
    steps: [
      "Sow in a nursery, transplant at pencil thickness.",
      "Space 10 cm apart in rows 30 cm apart.",
      "Stop watering when tops begin to fall.",
    ],
    water: "Steady until bulbing, then reduce.",
    pests: ["Thrips", "Downy mildew", "Purple blotch"],
    harvest: "Lift when half the tops have fallen; cure in shade.",
  },
  {
    id: "garlic",
    name: "Garlic",
    emoji: "🧄",
    gradient: "from-stone-200 to-violet-400",
    season: "Cool season",
    daysToHarvest: "150–210 days",
    yield: "6–12 t/ha",
    soils: ["loam", "sandy", "chalky"],
    tempMin: 8, tempMax: 24, rainMin: 0, rainMax: 70,
    reason: "Needs a cool start and a dry finish in well-drained soil.",
    steps: [
      "Split bulbs and plant single cloves 5 cm deep, tip up.",
      "Space 12 cm apart in rows 30 cm apart.",
      "Remove flower stalks to grow bigger bulbs.",
    ],
    water: "Moderate; stop 2–3 weeks before harvest.",
    pests: ["Rust", "White rot", "Thrips"],
    harvest: "Lift when the lower third of leaves are brown.",
  },
  {
    id: "cabbage",
    name: "Cabbage",
    emoji: "🥬",
    gradient: "from-emerald-200 to-green-600",
    season: "Cool season",
    daysToHarvest: "70–110 days",
    yield: "25–50 t/ha",
    soils: ["loam", "clay", "silty"],
    tempMin: 8, tempMax: 24, rainMin: 15, rainMax: 140,
    reason: "Heavy feeder that likes cool weather and moisture-retentive soil.",
    steps: [
      "Transplant 4-week seedlings 45 cm apart.",
      "Feed nitrogen 3 weeks after transplanting.",
      "Rotate away from other brassicas for 3 years.",
    ],
    water: "Consistent moisture prevents splitting.",
    pests: ["Diamondback moth", "Aphids", "Black rot"],
    harvest: "Cut when heads are firm and solid.",
  },
  {
    id: "carrot",
    name: "Carrot",
    emoji: "🥕",
    gradient: "from-orange-200 to-orange-600",
    season: "Cool season",
    daysToHarvest: "70–110 days",
    yield: "20–40 t/ha",
    soils: ["sandy", "loam", "silty"],
    tempMin: 8, tempMax: 25, rainMin: 10, rainMax: 100,
    reason: "Needs deep, loose, stone-free soil for straight roots.",
    steps: [
      "Sow thinly 1 cm deep directly in the bed.",
      "Thin to 5 cm apart at the 3-leaf stage.",
      "Keep the surface moist until germination.",
    ],
    water: "Even moisture stops roots splitting.",
    pests: ["Carrot fly", "Leaf blight"],
    harvest: "Pull when shoulders reach 2–3 cm across.",
  },
  {
    id: "lettuce",
    name: "Lettuce",
    emoji: "🥬",
    gradient: "from-lime-200 to-emerald-500",
    season: "Cool season",
    daysToHarvest: "40–70 days",
    yield: "15–30 t/ha",
    soils: ["loam", "silty", "peaty"],
    tempMin: 7, tempMax: 24, rainMin: 15, rainMax: 130,
    reason: "Fast salad crop for cool weather and steady moisture.",
    steps: [
      "Sow shallow and keep the bed damp.",
      "Thin or transplant to 25 cm apart.",
      "Harvest in the cool of the morning.",
    ],
    water: "Frequent light watering; never let it wilt.",
    pests: ["Aphids", "Slugs", "Downy mildew"],
    harvest: "Cut whole heads when firm, before bolting.",
  },
  {
    id: "spinach",
    name: "Spinach",
    emoji: "🥬",
    gradient: "from-green-300 to-emerald-700",
    season: "Cool season",
    daysToHarvest: "35–60 days",
    yield: "10–20 t/ha",
    soils: ["loam", "silty", "peaty"],
    tempMin: 5, tempMax: 22, rainMin: 15, rainMax: 140,
    reason: "Quick leafy green that bolts in heat but loves cool damp soil.",
    steps: [
      "Sow 2 cm deep in rows 25 cm apart.",
      "Thin to 10 cm.",
      "Pick outer leaves regularly to extend harvest.",
    ],
    water: "Keep the soil evenly moist.",
    pests: ["Leaf miner", "Downy mildew"],
    harvest: "Cut leaves from 6 weeks onwards.",
  },
  {
    id: "okra",
    name: "Okra",
    emoji: "🌿",
    gradient: "from-green-200 to-lime-600",
    season: "Hot season",
    daysToHarvest: "50–80 days",
    yield: "8–15 t/ha",
    soils: ["loam", "sandy", "silty"],
    tempMin: 20, tempMax: 36, rainMin: 5, rainMax: 120,
    reason: "Heat-loving vegetable that keeps producing for months.",
    steps: [
      "Soak seed overnight, sow 2 cm deep.",
      "Space 40 cm apart in rows 75 cm apart.",
      "Pick pods every 2 days to keep plants producing.",
    ],
    water: "Moderate; drought-tolerant once established.",
    pests: ["Fruit borer", "Aphids", "Powdery mildew"],
    harvest: "Cut pods young at 7–10 cm — older pods go woody.",
  },
  {
    id: "pepper",
    name: "Chilli / Sweet Pepper",
    emoji: "🌶️",
    gradient: "from-red-200 to-red-600",
    season: "Warm season",
    daysToHarvest: "80–120 days",
    yield: "10–25 t/ha",
    soils: ["loam", "sandy", "silty"],
    tempMin: 18, tempMax: 33, rainMin: 5, rainMax: 100,
    reason: "High-value warm-season crop for well-drained fertile soil.",
    steps: [
      "Raise seedlings for 5–6 weeks.",
      "Transplant 45 cm apart.",
      "Mulch and stake heavy-bearing plants.",
    ],
    water: "Regular; avoid soaking the crown.",
    pests: ["Thrips", "Aphids", "Anthracnose"],
    harvest: "Pick green or wait for full colour.",
  },
  {
    id: "eggplant",
    name: "Eggplant (Brinjal)",
    emoji: "🍆",
    gradient: "from-purple-300 to-violet-700",
    season: "Warm season",
    daysToHarvest: "80–120 days",
    yield: "15–35 t/ha",
    soils: ["loam", "sandy", "silty"],
    tempMin: 20, tempMax: 35, rainMin: 5, rainMax: 110,
    reason: "Long-bearing warm-season vegetable with strong market demand.",
    steps: [
      "Transplant 6-week seedlings 60 cm apart.",
      "Stake plants once fruit sets.",
      "Remove borer-damaged shoots promptly.",
    ],
    water: "Steady moisture; mulch heavily.",
    pests: ["Shoot and fruit borer", "Whitefly"],
    harvest: "Pick when the skin is glossy and springs back.",
  },
  {
    id: "cucumber",
    name: "Cucumber",
    emoji: "🥒",
    gradient: "from-lime-200 to-green-600",
    season: "Warm season",
    daysToHarvest: "45–70 days",
    yield: "20–40 t/ha",
    soils: ["loam", "sandy", "silty"],
    tempMin: 18, tempMax: 33, rainMin: 15, rainMax: 130,
    reason: "Fast vine crop for warm weather and rich, moist soil.",
    steps: [
      "Sow 2 seeds per station, 45 cm apart.",
      "Trellis vines to keep fruit clean.",
      "Harvest every 2 days at peak.",
    ],
    water: "High and consistent — dryness makes bitter fruit.",
    pests: ["Downy mildew", "Cucumber beetle", "Aphids"],
    harvest: "Pick young and firm before seeds harden.",
  },
  {
    id: "pumpkin",
    name: "Pumpkin / Squash",
    emoji: "🎃",
    gradient: "from-orange-200 to-amber-600",
    season: "Warm season",
    daysToHarvest: "90–130 days",
    yield: "15–30 t/ha",
    soils: ["loam", "sandy", "clay"],
    tempMin: 18, tempMax: 34, rainMin: 10, rainMax: 140,
    reason: "Low-input sprawling crop that smothers weeds and stores well.",
    steps: [
      "Plant 2–3 seeds per hill, hills 2 m apart.",
      "Add compost to each planting hill.",
      "Turn fruit occasionally to colour evenly.",
    ],
    water: "Deep watering weekly.",
    pests: ["Powdery mildew", "Fruit fly", "Squash bug"],
    harvest: "Skin is hard and the stem has corked.",
  },
  {
    id: "watermelon",
    name: "Watermelon",
    emoji: "🍉",
    gradient: "from-green-300 to-rose-500",
    season: "Hot, dry season",
    daysToHarvest: "80–110 days",
    yield: "20–45 t/ha",
    soils: ["sandy", "loam"],
    tempMin: 21, tempMax: 36, rainMin: 0, rainMax: 80,
    reason: "Needs heat, sun and sandy soil with a dry ripening period.",
    steps: [
      "Sow on raised beds 1.5 m apart.",
      "Mulch to keep fruit off wet soil.",
      "Reduce water as fruit ripens for sweetness.",
    ],
    water: "Moderate early, low late.",
    pests: ["Aphids", "Fruit fly", "Anthracnose"],
    harvest: "Tendril nearest the fruit dries and the base turns cream.",
  },
  {
    id: "banana",
    name: "Banana / Plantain",
    emoji: "🍌",
    gradient: "from-yellow-200 to-lime-500",
    season: "Year-round (tropical)",
    daysToHarvest: "9–14 months",
    yield: "20–50 t/ha",
    soils: ["loam", "silty", "clay"],
    tempMin: 20, tempMax: 34, rainMin: 30, rainMax: 300,
    reason: "Perennial tropical crop needing warmth and reliable moisture.",
    steps: [
      "Plant clean suckers in 60 cm pits with compost.",
      "Space 3 m x 3 m.",
      "Desucker to 3 followers per mat and prop heavy bunches.",
    ],
    water: "High — 25 mm per week minimum.",
    pests: ["Banana weevil", "Nematodes", "Panama disease"],
    harvest: "Cut when fingers are full and rounded.",
  },
  {
    id: "sugarcane",
    name: "Sugarcane",
    emoji: "🎋",
    gradient: "from-lime-300 to-green-700",
    season: "Long warm season",
    daysToHarvest: "10–18 months",
    yield: "60–100 t/ha",
    soils: ["loam", "clay", "silty"],
    tempMin: 21, tempMax: 36, rainMin: 30, rainMax: 300,
    reason: "High-yield industrial crop for hot climates with plenty of water.",
    steps: [
      "Plant 3-bud setts in 20 cm furrows.",
      "Earth up as shoots emerge.",
      "Apply nitrogen and potash at tillering.",
    ],
    water: "Very high water demand throughout growth.",
    pests: ["Stem borer", "Smut", "White grub"],
    harvest: "Cut at the base when sugar content peaks.",
  },
  {
    id: "coffee",
    name: "Coffee",
    emoji: "☕",
    gradient: "from-stone-300 to-amber-800",
    season: "Perennial (highland)",
    daysToHarvest: "3 years to first crop",
    yield: "1–3 t/ha green beans",
    soils: ["loam", "peaty", "silty"],
    tempMin: 15, tempMax: 27, rainMin: 25, rainMax: 200,
    reason: "Highland perennial that needs mild temperatures and deep soil.",
    steps: [
      "Plant seedlings 2 m apart in 60 cm pits with compost.",
      "Provide light shade trees.",
      "Prune annually to keep bearing wood young.",
    ],
    water: "1200–1800 mm a year, well distributed.",
    pests: ["Coffee berry borer", "Leaf rust"],
    harvest: "Pick only fully red cherries, in several passes.",
  },
  {
    id: "tea",
    name: "Tea",
    emoji: "🍵",
    gradient: "from-emerald-300 to-green-800",
    season: "Perennial (highland)",
    daysToHarvest: "3–4 years to first plucking",
    yield: "2–4 t/ha made tea",
    soils: ["peaty", "loam", "silty"],
    tempMin: 13, tempMax: 28, rainMin: 30, rainMax: 300,
    reason: "Acid-loving highland perennial for high rainfall areas.",
    steps: [
      "Plant clonal cuttings 1.2 m apart on contours.",
      "Peg and prune to form a flat plucking table.",
      "Pluck two leaves and a bud every 7–14 days.",
    ],
    water: "High, evenly spread rainfall.",
    pests: ["Tea mosquito bug", "Red spider mite"],
    harvest: "Continuous plucking once the table forms.",
  },
  {
    id: "cotton",
    name: "Cotton",
    emoji: "🧵",
    gradient: "from-stone-100 to-amber-300",
    season: "Long warm season",
    daysToHarvest: "150–180 days",
    yield: "1.5–3 t/ha seed cotton",
    soils: ["loam", "clay", "silty"],
    tempMin: 20, tempMax: 37, rainMin: 5, rainMax: 120,
    reason: "Cash crop for hot climates with a dry harvest window.",
    steps: [
      "Sow 3 cm deep in rows 90 cm apart.",
      "Thin to one plant every 25 cm.",
      "Scout weekly for bollworm from squaring.",
    ],
    water: "Moderate; dry weather needed at boll opening.",
    pests: ["Bollworm", "Whitefly", "Jassids"],
    harvest: "Pick when bolls open fully and lint is dry.",
  },
  {
    id: "sunflower",
    name: "Sunflower",
    emoji: "🌻",
    gradient: "from-yellow-200 to-amber-600",
    season: "Warm season",
    daysToHarvest: "90–120 days",
    yield: "1–2.5 t/ha",
    soils: ["loam", "sandy", "clay", "chalky"],
    tempMin: 15, tempMax: 33, rainMin: 5, rainMax: 110,
    reason: "Deep-rooted oilseed that copes with dry spells and many soils.",
    steps: [
      "Sow 4 cm deep in rows 60 cm apart.",
      "Thin to 25 cm between plants.",
      "Bird-protect heads as seeds fill.",
    ],
    water: "Low to moderate; deep roots find moisture.",
    pests: ["Birds", "Downy mildew", "Head rot"],
    harvest: "Backs of heads turn brown and seeds loosen.",
  },
  {
    id: "sesame",
    name: "Sesame",
    emoji: "🌱",
    gradient: "from-amber-100 to-yellow-500",
    season: "Hot season",
    daysToHarvest: "90–120 days",
    yield: "0.5–1.5 t/ha",
    soils: ["sandy", "loam"],
    tempMin: 22, tempMax: 38, rainMin: 0, rainMax: 80,
    reason: "Drought-tolerant oilseed for hot, light, well-drained land.",
    steps: [
      "Sow very shallow (1–2 cm) into a fine seedbed.",
      "Thin to 10 cm apart.",
      "Harvest before capsules shatter.",
    ],
    water: "Low; hates waterlogging.",
    pests: ["Webworm", "Bacterial blight"],
    harvest: "Cut when lower capsules turn yellow-brown; dry on sheets.",
  },
  {
    id: "ginger",
    name: "Ginger",
    emoji: "🫚",
    gradient: "from-amber-200 to-yellow-600",
    season: "Warm, wet season",
    daysToHarvest: "8–10 months",
    yield: "10–20 t/ha",
    soils: ["loam", "silty", "peaty"],
    tempMin: 20, tempMax: 32, rainMin: 30, rainMax: 250,
    reason: "Shade-tolerant, high-value rhizome for rich moist soil.",
    steps: [
      "Plant healthy rhizome pieces 5 cm deep on raised beds.",
      "Mulch thickly to hold moisture.",
      "Earth up twice during growth.",
    ],
    water: "High but never waterlogged.",
    pests: ["Rhizome rot", "Shoot borer"],
    harvest: "Lift when leaves yellow and dry off.",
  },
  {
    id: "turmeric",
    name: "Turmeric",
    emoji: "🟠",
    gradient: "from-yellow-300 to-orange-600",
    season: "Warm, wet season",
    daysToHarvest: "7–9 months",
    yield: "10–25 t/ha",
    soils: ["loam", "silty", "clay"],
    tempMin: 20, tempMax: 33, rainMin: 25, rainMax: 250,
    reason: "Spice rhizome that suits warm humid areas with fertile soil.",
    steps: [
      "Plant mother rhizomes 5 cm deep, 25 cm apart.",
      "Mulch with green leaves after planting.",
      "Weed and earth up at 60 and 120 days.",
    ],
    water: "Regular; good drainage essential.",
    pests: ["Rhizome scale", "Leaf blotch"],
    harvest: "Dig when leaves dry; boil and dry rhizomes.",
  },
  {
    id: "pineapple",
    name: "Pineapple",
    emoji: "🍍",
    gradient: "from-yellow-200 to-lime-600",
    season: "Warm season",
    daysToHarvest: "15–20 months",
    yield: "35–60 t/ha",
    soils: ["sandy", "loam", "peaty"],
    tempMin: 20, tempMax: 34, rainMin: 10, rainMax: 200,
    reason: "Tolerates acidic, sandy soils and irregular rainfall.",
    steps: [
      "Plant suckers 30 cm apart in double rows.",
      "Mulch with plastic or grass to suppress weeds.",
      "Force flowering uniformly for one harvest window.",
    ],
    water: "Moderate; very drought hardy.",
    pests: ["Mealybug wilt", "Nematodes"],
    harvest: "Shell turns golden at the base and the fruit smells sweet.",
  },
  {
    id: "mango",
    name: "Mango",
    emoji: "🥭",
    gradient: "from-amber-200 to-rose-500",
    season: "Perennial (tropical)",
    daysToHarvest: "3–5 years to first fruit",
    yield: "10–25 t/ha",
    soils: ["loam", "sandy", "chalky"],
    tempMin: 20, tempMax: 38, rainMin: 0, rainMax: 150,
    reason: "Deep-rooted tree that needs a dry spell to flower well.",
    steps: [
      "Plant grafted seedlings in 1 m pits, 8 m apart.",
      "Water for the first two dry seasons.",
      "Prune after harvest to keep an open canopy.",
    ],
    water: "Low once established; dry period triggers flowering.",
    pests: ["Fruit fly", "Powdery mildew", "Anthracnose"],
    harvest: "Shoulders fill out and flesh near the stone turns yellow.",
  },
  {
    id: "avocado",
    name: "Avocado",
    emoji: "🥑",
    gradient: "from-lime-300 to-emerald-700",
    season: "Perennial",
    daysToHarvest: "3–4 years to first fruit",
    yield: "10–20 t/ha",
    soils: ["loam", "sandy", "silty"],
    tempMin: 15, tempMax: 30, rainMin: 15, rainMax: 200,
    reason: "High-value tree crop, but needs very free-draining soil.",
    steps: [
      "Plant grafted trees on mounds 7 m apart.",
      "Mulch widely but keep mulch off the trunk.",
      "Never allow water to stand around roots.",
    ],
    water: "Regular but well-drained; root rot is the main risk.",
    pests: ["Phytophthora root rot", "Thrips", "Fruit fly"],
    harvest: "Fruit matures on the tree, softens after picking.",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    emoji: "🍓",
    gradient: "from-rose-200 to-red-600",
    season: "Cool season",
    daysToHarvest: "60–90 days from runners",
    yield: "10–25 t/ha",
    soils: ["loam", "sandy", "peaty"],
    tempMin: 8, tempMax: 26, rainMin: 10, rainMax: 120,
    reason: "Cool-climate high-value fruit for slightly acidic soils.",
    steps: [
      "Plant runners on raised beds 30 cm apart.",
      "Mulch with straw to keep fruit clean.",
      "Remove runners to build up crowns.",
    ],
    water: "Frequent light watering; drip is best.",
    pests: ["Grey mould", "Red spider mite", "Birds"],
    harvest: "Pick fully red fruit with the calyx attached.",
  },
  {
    id: "sorghum-sweet",
    name: "Finger Millet",
    emoji: "🌾",
    gradient: "from-red-200 to-amber-700",
    season: "Warm season",
    daysToHarvest: "100–140 days",
    yield: "1–3 t/ha",
    soils: ["loam", "sandy", "clay"],
    tempMin: 18, tempMax: 33, rainMin: 10, rainMax: 130,
    reason: "Nutritious, storable cereal that tolerates marginal soils.",
    steps: [
      "Sow shallow into a fine, firm seedbed.",
      "Weed carefully at 3 weeks — seedlings are tiny.",
      "Top-dress nitrogen at tillering.",
    ],
    water: "Moderate; tolerates short dry spells.",
    pests: ["Blast", "Birds"],
    harvest: "Cut heads when grains harden and darken.",
  },
  {
    id: "taro",
    name: "Taro (Cocoyam)",
    emoji: "🥥",
    gradient: "from-emerald-200 to-teal-700",
    season: "Warm, wet season",
    daysToHarvest: "6–12 months",
    yield: "10–25 t/ha",
    soils: ["clay", "silty", "peaty"],
    tempMin: 20, tempMax: 33, rainMin: 40, rainMax: 350,
    reason: "One of the few root crops that thrives in wet, heavy ground.",
    steps: [
      "Plant corm tops 10 cm deep in moist beds.",
      "Space 60 cm apart.",
      "Keep soil constantly damp; flooded beds work well.",
    ],
    water: "Very high — tolerates standing water.",
    pests: ["Taro leaf blight", "Aphids"],
    harvest: "Lift when leaves yellow and fall over.",
  },
];
