import type { Crop } from "./crops";

/**
 * Herbs, spices, nuts and extra food plants so the library covers just about
 * anything a farmer or gardener may want to plant.
 */
export const MORE_CROPS: Crop[] = [
  {
    id: "basil", name: "Basil", emoji: "🌿", gradient: "from-green-200 to-emerald-500",
    season: "Warm season", daysToHarvest: "50–70 days", yield: "5–10 t/ha",
    soils: ["loam", "sandy", "silty"], tempMin: 18, tempMax: 32, rainMin: 10, rainMax: 90,
    reason: "Fast, high-value herb that grows well in pots, gardens and fields.",
    steps: [
      "Sow seed 0.5 cm deep in a nursery tray or fine seedbed.",
      "Transplant strong seedlings 30 cm apart when they have 4 true leaves.",
      "Pinch off the growing tip every 2 weeks to make the plant bushy.",
      "Remove flower heads as soon as they appear to keep leaves sweet.",
    ],
    water: "Keep the soil lightly moist. Water little and often.",
    pests: ["Aphids", "Whitefly", "Downy mildew"],
    harvest: "Cut leafy stems from above a leaf pair; the plant regrows in 2–3 weeks.",
  },
  {
    id: "coriander", name: "Coriander (Dhania)", emoji: "🌿", gradient: "from-lime-200 to-green-500",
    season: "Cool to warm", daysToHarvest: "40–60 days", yield: "6–10 t/ha",
    soils: ["loam", "silty", "sandy"], tempMin: 12, tempMax: 28, rainMin: 10, rainMax: 80,
    reason: "Very quick market herb you can harvest within two months.",
    steps: [
      "Rub the round seeds gently to split them, then soak overnight.",
      "Sow directly 1–2 cm deep in rows 20 cm apart.",
      "Thin seedlings to 10 cm apart.",
      "Sow a new row every 3 weeks for a steady supply.",
    ],
    water: "Light, frequent watering. It bolts in hot dry soil.",
    pests: ["Aphids", "Leaf spot"],
    harvest: "Pull or cut whole plants when 15–20 cm tall, before flowering.",
  },
  {
    id: "mint", name: "Mint", emoji: "🌿", gradient: "from-emerald-200 to-teal-500",
    season: "Year-round", daysToHarvest: "60–90 days", yield: "8–15 t/ha",
    soils: ["loam", "silty", "peaty", "clay"], tempMin: 12, tempMax: 30, rainMin: 20, rainMax: 150,
    reason: "Hardy perennial herb that spreads fast and needs little care.",
    steps: [
      "Take 10 cm cuttings or root runners from a healthy plant.",
      "Plant 30 cm apart in a moist, half-shaded bed.",
      "Grow in a sunken tin or bed edge — mint spreads and takes over.",
      "Cut back hard after flowering to get fresh leaves.",
    ],
    water: "Likes damp soil. Never let it dry out completely.",
    pests: ["Mint rust", "Spider mites"],
    harvest: "Cut stems as needed; the plant regrows all season.",
  },
  {
    id: "chilli", name: "Chilli Pepper", emoji: "🌶️", gradient: "from-red-300 to-rose-600",
    season: "Warm season", daysToHarvest: "90–120 days", yield: "8–15 t/ha",
    soils: ["loam", "sandy", "silty"], tempMin: 20, tempMax: 35, rainMin: 5, rainMax: 80,
    reason: "High-value crop that keeps producing for months in warm weather.",
    steps: [
      "Raise seedlings in a nursery for 5–6 weeks.",
      "Transplant 45 cm apart into composted beds.",
      "Stake tall varieties so heavy branches do not break.",
      "Pick regularly — the more you pick the more it flowers.",
    ],
    water: "Deep watering twice a week. Avoid waterlogging.",
    pests: ["Thrips", "Aphids", "Fruit fly", "Anthracnose"],
    harvest: "Pick green for fresh use or wait for full red colour for drying.",
  },
  {
    id: "garlic", name: "Garlic", emoji: "🧄", gradient: "from-stone-200 to-purple-300",
    season: "Cool season", daysToHarvest: "120–180 days", yield: "8–12 t/ha",
    soils: ["loam", "sandy", "silty"], tempMin: 10, tempMax: 26, rainMin: 5, rainMax: 60,
    reason: "Stores for many months and sells well long after harvest.",
    steps: [
      "Split a healthy bulb into cloves just before planting.",
      "Plant cloves pointed end up, 5 cm deep and 12 cm apart.",
      "Mulch the bed to keep weeds down and moisture even.",
      "Stop watering when the lower leaves start to yellow.",
    ],
    water: "Even moisture while the bulb swells, dry at the end.",
    pests: ["Thrips", "White rot"],
    harvest: "Lift when half the leaves are brown; cure in shade for 2 weeks.",
  },
  {
    id: "ginger", name: "Ginger", emoji: "🫚", gradient: "from-amber-200 to-yellow-600",
    season: "Warm wet season", daysToHarvest: "8–10 months", yield: "15–25 t/ha",
    soils: ["loam", "silty", "peaty"], tempMin: 20, tempMax: 32, rainMin: 40, rainMax: 250,
    reason: "Shade-tolerant spice with strong prices and long storage.",
    steps: [
      "Cut rhizomes into 4–5 cm pieces, each with 2 buds; dry the cuts for a day.",
      "Plant 5 cm deep on ridges, 25 cm apart, in partial shade.",
      "Mulch thickly with dry grass right after planting.",
      "Earth up around the plants twice as the rhizomes swell.",
    ],
    water: "Needs steady moisture but never standing water.",
    pests: ["Rhizome rot", "Shoot borer"],
    harvest: "Dig up when leaves yellow and dry, 8–10 months after planting.",
  },
  {
    id: "turmeric", name: "Turmeric", emoji: "🟠", gradient: "from-orange-200 to-amber-600",
    season: "Warm wet season", daysToHarvest: "8–9 months", yield: "20–30 t/ha",
    soils: ["loam", "silty", "clay"], tempMin: 20, tempMax: 33, rainMin: 40, rainMax: 250,
    reason: "Hardy spice rhizome that grows under light shade with few pests.",
    steps: [
      "Select healthy mother rhizomes with 2–3 buds.",
      "Plant 5 cm deep on ridges 30 cm apart.",
      "Mulch heavily and repeat after 45 days.",
      "Weed by hand — the shoots are easily damaged.",
    ],
    water: "Keep moist through the growing season; dry off before harvest.",
    pests: ["Leaf blotch", "Rhizome scale"],
    harvest: "Lift when leaves dry; boil, then dry the rhizomes for market.",
  },
  {
    id: "lemongrass", name: "Lemongrass", emoji: "🌾", gradient: "from-lime-200 to-emerald-400",
    season: "Year-round", daysToHarvest: "4–6 months", yield: "15–25 t/ha",
    soils: ["sandy", "loam", "silty"], tempMin: 18, tempMax: 35, rainMin: 10, rainMax: 200,
    reason: "Tough perennial grass for tea and oil; also holds soil on slopes.",
    steps: [
      "Split a clump into single slips with roots attached.",
      "Trim the tops and plant 60 cm apart.",
      "Weed for the first 2 months until the clump closes.",
      "Cut back to 15 cm after each harvest to force new shoots.",
    ],
    water: "Very drought hardy once established.",
    pests: ["Rust", "Stem borer"],
    harvest: "Cut mature stems at ground level from 4 months, several times a year.",
  },
  {
    id: "moringa", name: "Moringa", emoji: "🌳", gradient: "from-green-200 to-lime-600",
    season: "Year-round", daysToHarvest: "6–8 months", yield: "20–40 t/ha leaves",
    soils: ["sandy", "loam", "chalky"], tempMin: 20, tempMax: 38, rainMin: 0, rainMax: 150,
    reason: "Fast-growing, drought-proof tree with very nutritious leaves.",
    steps: [
      "Sow seed 2 cm deep directly where the tree will grow, or plant 1 m cuttings.",
      "Space 1 m apart for leaf production, 3 m apart for pods.",
      "Cut the top at 1 m to make the tree branch low and easy to pick.",
      "Prune hard after each harvest to keep fresh leaves coming.",
    ],
    water: "Water for the first 2 months only; after that rain is enough.",
    pests: ["Caterpillars", "Termites"],
    harvest: "Strip leaves from 6 months; pods from the second year.",
  },
  {
    id: "amaranth", name: "Amaranth (Terere)", emoji: "🥬", gradient: "from-rose-200 to-green-500",
    season: "Warm season", daysToHarvest: "30–50 days", yield: "10–20 t/ha",
    soils: ["loam", "sandy", "silty", "clay"], tempMin: 18, tempMax: 35, rainMin: 10, rainMax: 120,
    reason: "One of the fastest, cheapest leafy vegetables and very nutritious.",
    steps: [
      "Mix the tiny seed with dry sand so you can spread it evenly.",
      "Broadcast or drill 1 cm deep on a fine, flat bed.",
      "Thin to 15 cm apart and eat the thinnings.",
      "Top-dress with manure tea after the first cutting.",
    ],
    water: "Water daily in dry weather — leaves must stay soft.",
    pests: ["Leaf miner", "Aphids"],
    harvest: "Cut whole plants at 30 days or pick leaves repeatedly.",
  },
  {
    id: "kale", name: "Kale (Sukuma Wiki)", emoji: "🥬", gradient: "from-green-300 to-teal-600",
    season: "Cool to warm", daysToHarvest: "50–70 days", yield: "25–40 t/ha",
    soils: ["loam", "silty", "clay"], tempMin: 10, tempMax: 28, rainMin: 15, rainMax: 120,
    reason: "Picks leaf by leaf for months — steady food and steady income.",
    steps: [
      "Raise seedlings for 4 weeks in a shaded nursery.",
      "Transplant 40 cm apart in well-manured beds.",
      "Top-dress with nitrogen 3 weeks after transplanting.",
      "Pick the lower leaves first and leave the growing tip.",
    ],
    water: "Water 2–3 times a week; leaves get bitter when dry.",
    pests: ["Diamondback moth", "Aphids", "Black rot"],
    harvest: "Start picking outer leaves 6–8 weeks after transplanting.",
  },
  {
    id: "swiss_chard", name: "Swiss Chard (Spinach)", emoji: "🥬", gradient: "from-emerald-200 to-red-400",
    season: "Cool to warm", daysToHarvest: "50–60 days", yield: "20–35 t/ha",
    soils: ["loam", "silty", "clay"], tempMin: 10, tempMax: 30, rainMin: 15, rainMax: 120,
    reason: "Cut-and-come-again leaf crop that keeps producing for months.",
    steps: [
      "Soak seed overnight and sow 2 cm deep.",
      "Thin or transplant to 30 cm apart.",
      "Feed with compost or manure tea every month.",
      "Remove old outer leaves to keep new ones coming.",
    ],
    water: "Even moisture; mulch to protect shallow roots.",
    pests: ["Leaf miner", "Cercospora leaf spot"],
    harvest: "Cut outer leaves from 7 weeks, every week after that.",
  },
  {
    id: "cauliflower", name: "Cauliflower", emoji: "🥦", gradient: "from-stone-100 to-lime-300",
    season: "Cool season", daysToHarvest: "80–110 days", yield: "20–30 t/ha",
    soils: ["loam", "silty", "clay"], tempMin: 10, tempMax: 24, rainMin: 15, rainMax: 100,
    reason: "Cool-weather cash crop for fertile, well-drained soils.",
    steps: [
      "Raise seedlings for 4–5 weeks.",
      "Transplant 50 cm apart into rich, limed soil.",
      "Fold outer leaves over the head to keep it white.",
      "Feed with nitrogen 3 and 6 weeks after transplanting.",
    ],
    water: "Never let it dry out or the heads stay small.",
    pests: ["Diamondback moth", "Club root", "Aphids"],
    harvest: "Cut while the head is tight, firm and still smooth.",
  },
  {
    id: "broccoli", name: "Broccoli", emoji: "🥦", gradient: "from-green-300 to-emerald-600",
    season: "Cool season", daysToHarvest: "80–100 days", yield: "12–20 t/ha",
    soils: ["loam", "silty"], tempMin: 10, tempMax: 24, rainMin: 15, rainMax: 100,
    reason: "Cool-season vegetable with strong demand in towns and hotels.",
    steps: [
      "Raise seedlings for 4 weeks.",
      "Transplant 45 cm apart on composted beds.",
      "Cut the main head early to get many side shoots.",
      "Keep the soil mulched and cool.",
    ],
    water: "Water deeply twice a week.",
    pests: ["Cabbage worm", "Aphids"],
    harvest: "Cut the head while the buds are still tight and green.",
  },
  {
    id: "green_pea", name: "Garden Pea", emoji: "🫛", gradient: "from-lime-200 to-green-500",
    season: "Cool season", daysToHarvest: "60–90 days", yield: "4–8 t/ha",
    soils: ["loam", "silty", "sandy"], tempMin: 8, tempMax: 24, rainMin: 15, rainMax: 100,
    reason: "Cool-season legume that improves the soil for the next crop.",
    steps: [
      "Sow 3 cm deep, 8 cm apart in rows 45 cm apart.",
      "Put up sticks or wire for climbing types at sowing time.",
      "Do not add nitrogen fertiliser — peas make their own.",
      "Weed carefully; the roots are shallow.",
    ],
    water: "Water most at flowering and pod filling.",
    pests: ["Pea aphid", "Powdery mildew"],
    harvest: "Pick pods young and tender, every 2–3 days.",
  },
  {
    id: "pigeon_pea", name: "Pigeon Pea", emoji: "🫘", gradient: "from-amber-200 to-lime-600",
    season: "Warm season", daysToHarvest: "5–9 months", yield: "1–2 t/ha",
    soils: ["sandy", "loam", "clay"], tempMin: 18, tempMax: 35, rainMin: 5, rainMax: 120,
    reason: "Deep-rooted, drought-proof legume that also feeds the soil.",
    steps: [
      "Sow 3–5 cm deep, 50 cm apart in rows 1 m apart.",
      "Intercrop with maize or sorghum for extra income.",
      "Weed twice in the first 2 months.",
      "Cut back after harvest — the plant ratoons for a second year.",
    ],
    water: "Rain-fed. Very tolerant of dry spells.",
    pests: ["Pod borer", "Pod fly", "Fusarium wilt"],
    harvest: "Pick green pods for food, or let them dry for grain.",
  },
  {
    id: "cashew", name: "Cashew", emoji: "🌰", gradient: "from-amber-200 to-orange-500",
    season: "Perennial tree", daysToHarvest: "3–5 years", yield: "0.5–1.5 t/ha nuts",
    soils: ["sandy", "loam"], tempMin: 20, tempMax: 38, rainMin: 0, rainMax: 150,
    reason: "Drought-hardy tree crop for hot, sandy coastal land.",
    steps: [
      "Plant grafted seedlings at the start of the rains, 10 m apart.",
      "Dig 60 cm holes and mix in manure before planting.",
      "Protect young trees from livestock and fire for 3 years.",
      "Prune to open the centre and remove dead wood each year.",
    ],
    water: "Water young trees weekly for 2 years; mature trees are rain-fed.",
    pests: ["Helopeltis bug", "Powdery mildew"],
    harvest: "Collect fallen nuts, dry them in the sun for 2–3 days.",
  },
  {
    id: "macadamia", name: "Macadamia", emoji: "🌰", gradient: "from-stone-200 to-amber-500",
    season: "Perennial tree", daysToHarvest: "4–6 years", yield: "2–4 t/ha nuts",
    soils: ["loam", "silty", "peaty"], tempMin: 15, tempMax: 30, rainMin: 20, rainMax: 200,
    reason: "High-value export nut for deep, well-drained highland soils.",
    steps: [
      "Plant grafted seedlings 8 m apart in 60 cm holes with manure.",
      "Stake young trees and keep a 1 m weed-free ring.",
      "Mulch heavily — the roots sit close to the surface.",
      "Prune to a single leader in the first 3 years.",
    ],
    water: "Needs regular water in the first 3 years and during nut fill.",
    pests: ["Nut borer", "Stink bug"],
    harvest: "Gather nuts from the ground every 2 weeks; dehusk within a day.",
  },
  {
    id: "sunflower_seed", name: "Sunflower", emoji: "🌻", gradient: "from-yellow-200 to-amber-600",
    season: "Warm season", daysToHarvest: "90–120 days", yield: "1.5–3 t/ha",
    soils: ["loam", "sandy", "clay", "chalky"], tempMin: 18, tempMax: 32, rainMin: 10, rainMax: 120,
    reason: "Easy oil crop that copes with dry spells and poor soils.",
    steps: [
      "Sow 4 cm deep, 25 cm apart in rows 70 cm apart.",
      "Thin to one strong plant per station.",
      "Weed at 2 and 5 weeks.",
      "Scare birds from flowering until harvest.",
    ],
    water: "Deep roots find their own water; only water in long droughts.",
    pests: ["Birds", "Head rot", "Rust"],
    harvest: "Cut heads when the back turns brown and the seeds are hard.",
  },
  {
    id: "mushroom", name: "Oyster Mushroom", emoji: "🍄", gradient: "from-stone-200 to-slate-400",
    season: "Year-round indoors", daysToHarvest: "30–45 days", yield: "1–2 kg per bag",
    soils: ["loam"], tempMin: 15, tempMax: 30, rainMin: 0, rainMax: 400,
    reason: "Needs no land — grows indoors on straw and gives fast cash.",
    steps: [
      "Chop straw or maize stalks, soak overnight, then pasteurise in hot water.",
      "Drain until it holds no dripping water, then cool.",
      "Fill clear bags in layers: substrate, then a sprinkle of spawn.",
      "Keep bags dark at 20–28°C for 3 weeks, then cut slits and move to light.",
    ],
    water: "Mist the room 2–3 times a day to keep the air damp.",
    pests: ["Green mould", "Fungus gnats"],
    harvest: "Twist off whole clusters when the cap edges are still curled down.",
  },
  {
    id: "vanilla", name: "Vanilla", emoji: "🌺", gradient: "from-yellow-100 to-emerald-400",
    season: "Perennial vine", daysToHarvest: "3 years", yield: "0.3–0.6 t/ha",
    soils: ["loam", "peaty", "silty"], tempMin: 21, tempMax: 32, rainMin: 40, rainMax: 250,
    reason: "The world's most valuable spice for shaded, humid plots.",
    steps: [
      "Plant 1 m vine cuttings at the base of a living support tree under 50% shade.",
      "Loop the vine along a wire at chest height so you can reach the flowers.",
      "Hand-pollinate each flower in the morning with a small stick.",
      "Keep a thick leaf mulch over the shallow roots at all times.",
    ],
    water: "Needs humid air and moist mulch, never soggy soil.",
    pests: ["Fusarium root rot", "Snails"],
    harvest: "Pick pods 8–9 months after pollination, when the tip turns yellow.",
  },
  {
    id: "cocoa", name: "Cocoa", emoji: "🍫", gradient: "from-amber-300 to-yellow-800",
    season: "Perennial tree", daysToHarvest: "3–5 years", yield: "0.5–1.5 t/ha",
    soils: ["loam", "silty", "clay"], tempMin: 21, tempMax: 32, rainMin: 40, rainMax: 300,
    reason: "Long-term income tree for humid areas with shade.",
    steps: [
      "Plant shade trees (banana or gliricidia) a year before the cocoa.",
      "Plant seedlings 3 m apart in holes with manure.",
      "Weed a 1 m ring around each tree and mulch it.",
      "Prune yearly to keep the canopy open and remove black pods.",
    ],
    water: "Rain-fed in humid zones; irrigate young trees in dry spells.",
    pests: ["Black pod disease", "Capsid bug", "Mirids"],
    harvest: "Cut ripe yellow-orange pods with a knife, ferment beans 6 days, then dry.",
  },
  {
    id: "cocoyam", name: "Cocoyam", emoji: "🥔", gradient: "from-purple-200 to-emerald-500",
    season: "Wet season", daysToHarvest: "7–12 months", yield: "8–15 t/ha",
    soils: ["loam", "clay", "silty", "peaty"], tempMin: 20, tempMax: 32, rainMin: 40, rainMax: 300,
    reason: "Reliable root crop for wet, heavy soils where others rot.",
    steps: [
      "Select healthy corms or suckers as planting material.",
      "Plant 10 cm deep on mounds 1 m apart.",
      "Mulch heavily to hold moisture and stop weeds.",
      "Earth up around plants at 3 months.",
    ],
    water: "Loves wet ground and tolerates short flooding.",
    pests: ["Taro leaf blight", "Root rot"],
    harvest: "Lift corms when the leaves die back, from 7 months.",
  },
  {
    id: "plantain", name: "Plantain", emoji: "🍌", gradient: "from-lime-200 to-yellow-500",
    season: "Perennial", daysToHarvest: "9–14 months", yield: "15–30 t/ha",
    soils: ["loam", "silty", "peaty"], tempMin: 20, tempMax: 34, rainMin: 30, rainMax: 300,
    reason: "Staple food and steady income once the mat is established.",
    steps: [
      "Use clean sword suckers from a healthy, disease-free mat.",
      "Plant in 60 cm holes with manure, 3 m apart.",
      "Keep only 3 plants per mat: a mother, a daughter and a granddaughter.",
      "Prop heavy bunches with a forked stick.",
    ],
    water: "Needs steady moisture; mulch thickly with crop residue.",
    pests: ["Banana weevil", "Nematodes", "Black sigatoka"],
    harvest: "Cut the bunch when the fingers are full and round.",
  },
  {
    id: "sesbania", name: "Sesbania (Green Manure)", emoji: "🌱", gradient: "from-green-200 to-emerald-600",
    season: "Warm season", daysToHarvest: "60–90 days", yield: "20–40 t/ha biomass",
    soils: ["clay", "loam", "silty", "sandy"], tempMin: 18, tempMax: 36, rainMin: 10, rainMax: 250,
    reason: "Grown to be dug in — it feeds tired soil with free nitrogen.",
    steps: [
      "Broadcast seed thickly on the fallow plot after light rain.",
      "Let it grow 8–10 weeks until just before flowering.",
      "Slash the plants and chop them into short pieces.",
      "Dig or plough the green material into the soil and wait 2 weeks before planting.",
    ],
    water: "Rain-fed; it also survives waterlogged ground.",
    pests: ["Defoliating caterpillars"],
    harvest: "Not eaten — the harvest is richer soil and a better next crop.",
  },
  {
    id: "napier", name: "Napier Grass (Fodder)", emoji: "🌾", gradient: "from-lime-300 to-green-700",
    season: "Year-round", daysToHarvest: "90 days, then every 6–8 weeks", yield: "40–80 t/ha",
    soils: ["loam", "clay", "silty", "sandy"], tempMin: 15, tempMax: 35, rainMin: 20, rainMax: 300,
    reason: "Cheap, bulky animal feed that also stops soil washing away.",
    steps: [
      "Cut cane stems into pieces with 3 nodes each.",
      "Plant slanting, 2 nodes buried, 60 cm apart in rows 90 cm apart.",
      "Weed until the grass closes the rows.",
      "Apply manure or slurry after every cutting.",
    ],
    water: "Very hardy; grows back fast after rain.",
    pests: ["Napier stunt disease", "Head smut"],
    harvest: "Cut at 1–1.5 m tall, 10 cm above the ground, every 6–8 weeks.",
  },
];
